//! Prose documentation for stdlib intrinsics.
//!
//! GENERATED by `scripts/gen_stdlib_docs.py` from the doc comments on
//! the `IntrinsicId` variants in `crates/keron-lang/src/ast.rs` —
//! edit those comments and regenerate; do not edit this file by hand.
//! The `match` is exhaustive on purpose: adding a variant without
//! regenerating fails to compile.

use keron_lang::IntrinsicId;

/// First doc paragraph for `id`, in markdown. Empty when the variant
/// carries no doc comment.
// One arm per intrinsic by construction; length scales with the
// stdlib, not with complexity.
#[allow(clippy::too_many_lines)]
#[must_use]
pub const fn intrinsic_doc(id: IntrinsicId) -> &'static str {
    match id {
        IntrinsicId::Symlink => {
            "`symlink(source, target)` — declare a symbolic-link resource: apply creates the link at `target` pointing to `source` (resolved inside the keron root)."
        }
        IntrinsicId::Shell => {
            "`shell(kind, name, script)` — declare an explicit shell script resource. Planning verifies the named shell exists; execution feeds `script` to that shell on stdin."
        }
        IntrinsicId::Template => {
            "`template(source, target, vars)` — render a templated file. At apply time, `source` is read (resolved relative to the importing module's directory), `${name}` placeholders are substituted with values from `vars`, and the rendered text is written to `target`. Subsumes the old `file(target, content)` constructor: a non-templating file is just a `template` with an empty `vars` map."
        }
        IntrinsicId::KeronRoot => {
            "`keron_root()` — absolute path to the directory the user passed to `keron apply` (or the file's parent for the single-file case). Returned as a `String` so it can be interpolated into other path arguments."
        }
        IntrinsicId::OsType => {
            "`os_type()` — current OS as one of the `OsType` string-union variants (`\"Linux\"`, `\"Macos\"`, `\"Windows\"`, `\"Unknown\"`). Anything outside that set collapses to `\"Unknown\"`."
        }
        IntrinsicId::OsArch => {
            "`os_arch()` — current CPU architecture as one of the `OsArch` string-union variants. Falls back to `\"Unknown\"` when the host reports something we don't enumerate."
        }
        IntrinsicId::Env => {
            "`env(name)` — read an environment variable. Returns `String?`: the value when the variable is set (even if empty), or `null` when it is unset. Distinguishing \"unset\" from \"empty\" is the whole reason the return type is nullable rather than `String`."
        }
        IntrinsicId::Secret => {
            "`secret(uri)` — resolve an external secret URI into a `Secret` value. Eager: the URI is read at plan-build time and any resolution failure is a hard error."
        }
        IntrinsicId::UnwrapSecret => {
            "`unwrap_secret(s)` — convert a `Secret` to a `String`. The only legal way to extract; every call site is an audit breadcrumb for \"here is where the secret leaves the marker type and becomes plain text.\""
        }
        IntrinsicId::Brew => {
            "`brew(name, tap_url? = null)` — declares a Homebrew formula. The apply step runs `brew install`. A slash-qualified `name` of the form `user/tap/formula` declares the formula's tap inline; the optional `tap_url` overrides the auto-derived `homebrew-<tap>` GitHub URL for taps whose repo doesn't follow that naming convention. State is classified Create / `NoOp` by diffing against `brew list --formula -1` (bare-name match); `keron apply` only ensures presence and never upgrades an installed formula."
        }
        IntrinsicId::Cask => {
            "`cask(name, tap_url? = null)` — declares a Homebrew cask. The apply step runs `brew install --cask`. Same tap rules and same presence-only Create / `NoOp` classification as `Brew`, but diffed against the cask-side list (`brew list --cask -1`). Cask resources are macOS-only."
        }
        IntrinsicId::Cargo => {
            "`cargo(name)` — declares a `cargo install` binary. v1 carries only the crate name."
        }
        IntrinsicId::Winget => {
            "`winget(name)` — declares a winget package id (e.g. `\"Microsoft.PowerShell\"`). v1 carries only the id; sources can be added later as a second arg."
        }
        IntrinsicId::Hostname => {
            "`hostname()` — the host's network name. Resolved at evaluation time via `gethostname` on Unix and `$COMPUTERNAME` on Windows. Returns `String`; a syscall failure is a hard error (the failure mode is rare enough that wrapping every call site in a `??` would be noise, and a missing hostname usually signals a broken machine, not a manifest bug)."
        }
        IntrinsicId::User => {
            "`user()` — the invoking user's login name. Sourced from `$USER` on Unix and `$USERNAME` on Windows. Returns `String`; bails if neither is set (rare outside of CI sandboxes — those almost always set one of the two)."
        }
        IntrinsicId::HomeDir => {
            "`home_dir()` — the invoking user's home directory as an absolute path. Resolved via the `dirs` crate so the value matches the platform convention (`$HOME` on Unix, `%USERPROFILE%` on Windows). Returns `String`; bails if the crate can't determine it (effectively only when `$HOME` is unset and there's no fallback the OS can supply)."
        }
        IntrinsicId::ConfigDir => {
            "`config_dir()` — user config root. Linux: `$XDG_CONFIG_HOME` or `~/.config`. macOS: `~/Library/Application Support`. Windows: `%APPDATA%` (the roaming variant). Returns `String`; bails on the same failure mode as `HomeDir`."
        }
        IntrinsicId::CacheDir => {
            "`cache_dir()` — user cache root. Linux: `$XDG_CACHE_HOME` or `~/.cache`. macOS: `~/Library/Caches`. Windows: `%LOCALAPPDATA%`. Same failure model as `HomeDir`."
        }
        IntrinsicId::DataDir => {
            "`data_dir()` — user data root for things that may sync across machines. Linux: `$XDG_DATA_HOME` or `~/.local/share`. macOS: `~/Library/Application Support`. Windows: `%APPDATA%`. Same failure model as `HomeDir`."
        }
        IntrinsicId::StateDir => {
            "`state_dir()` — user state root for ephemeral-but-resumable data (Linux's XDG state slot). Linux: `$XDG_STATE_HOME` or `~/.local/state`. macOS and Windows: `null` — no platform equivalent exists, so the return type is `String?` and users must `??` a fallback (or `match` for OS-specific handling)."
        }
        IntrinsicId::RuntimeDir => {
            "`runtime_dir()` — user runtime root (Linux only). Linux: `$XDG_RUNTIME_DIR`. macOS and Windows: `null`. Returns `String?` for the same reason as `StateDir`."
        }
        IntrinsicId::Split => {
            "`split(s, sep)` — split `s` on every (non-overlapping) match of `sep`. Returns `List<String>`. An empty `sep` is an error (no well-defined split point). Result preserves empty pieces at the ends and between adjacent separators."
        }
        IntrinsicId::Join => {
            "`join(xs, sep)` — concatenate `xs` with `sep` between every pair. Returns `String`. Empty list produces `\"\"`."
        }
        IntrinsicId::Contains => {
            "`contains(x, item) -> Boolean` — type-directed membership: substring test on `String` (empty `item` is `true`, matching Rust's `str::contains`), element test on `List<T>` (same equality rule as `==`), key test on `Map<K, V>`. One name, one mental model — \"is this in that?\" — resolved by the checker from the first argument's type."
        }
        IntrinsicId::Replace => {
            "`replace(s, from, to)` — replace every (non-overlapping) occurrence of `from` in `s` with `to`. Empty `from` is an error."
        }
        IntrinsicId::Trim => "`trim(s)` — strip leading and trailing Unicode whitespace.",
        IntrinsicId::StartsWith => {
            "`starts_with(s, prefix) -> Boolean` — true when `s` begins with `prefix`. An empty `prefix` is `true` (matches Rust's `str::starts_with`). The canonical host-name gate (`if starts_with(hostname(), \"work-\") { … }`)."
        }
        IntrinsicId::EndsWith => {
            "`ends_with(s, suffix) -> Boolean` — true when `s` ends with `suffix`. An empty `suffix` is `true`."
        }
        IntrinsicId::Len => {
            "`len(x) -> Int` — type-directed size: Unicode scalar values (chars, not bytes) for `String`, element count for `List<T>`, entry count for `Map<K, V>`. Resolved by the checker from the argument's type."
        }
        IntrinsicId::ListFirst => {
            "`first(xs: List<T>) -> T?` — first element, or `null` for an empty list. Generic in `T`."
        }
        IntrinsicId::ListLast => {
            "`last(xs: List<T>) -> T?` — last element, or `null` for an empty list. Generic in `T`."
        }
        IntrinsicId::MapKeys => {
            "`keys(m: Map<K, V>) -> List<K>` — the map's keys in declared order. Generic in `K` and `V`."
        }
        IntrinsicId::MapValues => {
            "`values(m: Map<K, V>) -> List<V>` — the map's values in declared order. Generic in `K` and `V`."
        }
        IntrinsicId::MapGet => {
            "`get(m: Map<K, V>, k: K, default: V) -> V` — map lookup with a caller-supplied fallback. Returns the bound `V`; if a future release wants `V?`-returning lookup, that's a separate intrinsic. Generic in `K` and `V`."
        }
        IntrinsicId::PathJoin => {
            "`path_join(p: String, segment: String) -> String` — append `segment` to `p` with platform-native separator handling. If `segment` is absolute it replaces `p` (matching `PathBuf::join`), so users who concatenate `home_dir()` with a `${maybe_abs_var}` don't silently get a corrupted path."
        }
        IntrinsicId::PathParent => {
            "`path_parent(p: String) -> String?` — the directory portion of `p`, or `null` when `p` is a root (`/`, `C:\\`) or has no parent. Use `??` to thread the \"no parent\" case through."
        }
        IntrinsicId::PathBasename => {
            "`path_basename(p: String) -> String?` — the final component of `p` (file name, or last directory segment), or `null` for paths with no final component (`/`, `..`). Absence is `null` across the whole component family, matching `path_parent`."
        }
        IntrinsicId::PathExtension => {
            "`path_extension(p: String) -> String?` — the substring after the final `.` of the basename, or `null` when there is none. Mirrors `std::path::Path::extension` — leading-dot files (e.g. `.zshrc`) are treated as having no extension."
        }
        IntrinsicId::PathIsAbsolute => {
            "`path_is_absolute(p: String) -> Boolean` — true when `p` is a platform-absolute path (`/...` on Unix, `C:\\...` on Windows)."
        }
        IntrinsicId::PathExists => {
            "`path_exists(p: String) -> Boolean` — live host filesystem probe. It makes plan output depend on disk state at evaluation time; use sparingly and only for branching decisions the user expects to be live."
        }
        IntrinsicId::PathIsDir => {
            "`path_is_dir(p: String) -> Boolean` — `true` only when the path exists *and* is a directory (symlinks are followed)."
        }
        IntrinsicId::PathIsFile => {
            "`path_is_file(p: String) -> Boolean` — `true` only when the path exists *and* is a regular file (symlinks are followed)."
        }
        IntrinsicId::ReadFile => {
            "`read_file(path: String) -> String?` — load the UTF-8 contents of a file *inside the keron root* during evaluation. The path goes through the same `resolve_managed_path` containment check that `symlink(source = …)` and `template(source = …)` use, so a hostile manifest cannot read `/etc/passwd` or any host file the keron repo doesn't already include."
        }
        IntrinsicId::Sort => {
            "`sort(xs: List<T>) -> List<T>` — ascending order. Generic in `T` like its siblings, gated by the checker to orderable element types: `String` (Unicode codepoint order), `Int`, `Double`, and string unions. Mixed `Int`/`Double` lists order exactly (no `i64 → f64` promotion)."
        }
        IntrinsicId::Unique => {
            "`unique(xs: List<T>) -> List<T>` — preserve first occurrence, drop subsequent duplicates. Element equality follows the same rule as `==` / `contains`. Generic in `T`."
        }
        IntrinsicId::IndexOf => {
            "`index_of(xs: List<T>, x: T) -> Int?` — position of the first element equal to `x`, or `null` when absent. Returning `Int?` (not a sentinel `-1`) keeps the `??`-fallback path natural and avoids the \"is the index also a valid result?\" footgun. Generic in `T`."
        }
        IntrinsicId::MapMerge => {
            "`merge(a: Map<K, V>, b: Map<K, V>) -> Map<K, V>` — last-wins overlay: every binding of `b` shadows the same key in `a`. Preserves declaration order of `a`, with new keys from `b` appended. Generic in `K`, `V`."
        }
        IntrinsicId::MapWithout => {
            "`without(m: Map<K, V>, k: K) -> Map<K, V>` — drop the binding for `k` from `m`. No-op when `k` is absent (mirrors `Map::remove` when the caller doesn't need the removed value). Generic in `K`, `V`."
        }
        IntrinsicId::MapWith => {
            "`with(m: Map<K, V>, k: K, v: V) -> Map<K, V>` — insert or overwrite `k -> v`. When `k` is already bound, its position is preserved and only the value changes; otherwise the binding is appended. Generic in `K`, `V`."
        }
        IntrinsicId::ParseInt => {
            "`parse_int(s: String) -> Int?` — strict signed-integer parse. Accepts an optional leading `+`/`-` and ASCII digits only; returns `null` for any non-conforming input (whitespace, empty, trailing junk, hex prefixes, overflow). Use `trim(s)` first if you want to tolerate surrounding whitespace."
        }
        IntrinsicId::ParseDouble => {
            "`parse_double(s: String) -> Double?` — strict IEEE-754 parse via Rust's `str::parse::<f64>()`. Returns `null` for malformed input. NaN / infinity are not produced — Rust's parser accepts `\"inf\"`/`\"NaN\"`, so we screen those explicitly to keep `Double` values finite (the rest of the language assumes that)."
        }
        IntrinsicId::SshKey => {
            "`ssh_key(private_path, public_path, private, public)` — writes a user-supplied SSH keypair to disk as a single atomic resource. The `private` half flows in as `Type::Secret` (so a raw `String` is a typecheck error) and is written at mode `0600`; the `public` half is a `String` written at `0644`. `apply` only ensures *presence* — Create when the files are missing, `NoOp` when present and byte-identical, hard error when present with different content (refuses to silently rotate a key)."
        }
        IntrinsicId::GpgKey => {
            "`gpg_key(fingerprint, key)` — imports an ASCII-armored secret keyring blob into the user's gnupg keyring. `fingerprint` is the required idempotency probe (`gpg --batch --list-secret-keys <fingerprint>`, exit status only — never stdout capture). `key` flows in as `Type::Secret` and is piped to `gpg --batch --import` over child stdin (never argv, never a tempfile). `apply` only ensures *presence*: Create when the fingerprint is absent, `NoOp` when present."
        }
    }
}
