#!/usr/bin/env python3
"""Regenerate crates/keron-modules/src/stdlib_docs.rs.

Extracts the first doc-comment paragraph of every `IntrinsicId`
variant from crates/keron-lang/src/ast.rs and emits an exhaustive
`match` so a new variant without regeneration fails to compile.

Run from the repo root:  python3 scripts/gen_stdlib_docs.py
"""

import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
AST = ROOT / "crates/keron-lang/src/ast.rs"
OUT = ROOT / "crates/keron-modules/src/stdlib_docs.rs"

src = AST.read_text()
match = re.search(r"pub enum IntrinsicId \{(.*?)\n\}", src, re.DOTALL)
assert match, "IntrinsicId enum not found"
body = match.group(1)

variants: list[tuple[str, str]] = []
doc_lines: list[str] = []
for line in body.splitlines():
    stripped = line.strip()
    if stripped.startswith("///"):
        doc_lines.append(stripped[3:].strip())
    elif re.fullmatch(r"([A-Z][A-Za-z0-9]*),?", stripped):
        name = stripped.rstrip(",")
        # First paragraph only: cut at the first blank doc line.
        paragraph: list[str] = []
        for d in doc_lines:
            if not d:
                break
            paragraph.append(d)
        text = " ".join(paragraph)
        # Rustdoc intra-links ([`X`], [`X`](url)) render as noise in
        # hover markdown; collapse to plain code spans.
        text = re.sub(r"\[`([^`\]]+)`\]\([^)]*\)", r"`\1`", text)
        text = re.sub(r"\[`([^`\]]+)`\]", r"`\1`", text)
        text = re.sub(r"`Self::([A-Za-z0-9_]+)`", r"`\1`", text)
        variants.append((name, text))
        doc_lines = []
    elif stripped and not stripped.startswith("#["):
        doc_lines = []

assert len(variants) > 50, f"suspiciously few variants: {len(variants)}"


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


arms = "\n".join(
    f"        IntrinsicId::{name} => {rust_str(text)}," for name, text in variants
)

OUT.write_text(f'''//! Prose documentation for stdlib intrinsics, keyed by
//! [`IntrinsicId`]. GENERATED by `scripts/gen_stdlib_docs.py` from the
//! doc comments on the `IntrinsicId` variants in
//! `crates/keron-lang/src/ast.rs` — edit those comments and
//! regenerate; do not edit this file by hand. The `match` is
//! exhaustive on purpose: adding a variant without regenerating fails
//! to compile.

use keron_lang::IntrinsicId;

/// First doc paragraph for `id`, in markdown. Empty when the variant
/// carries no doc comment.
#[must_use]
pub const fn intrinsic_doc(id: IntrinsicId) -> &'static str {{
    match id {{
{arms}
    }}
}}
''')
print(f"wrote {OUT} with {len(variants)} variants")
